name: Continous Integration

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build and test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: checkout the code
      uses: actions/checkout@v3

    - name: Set up Java version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
      working-directory: ./PortalBackend/Java

    - name: Run Tests with Maven
      run: mvn -B test -Dspring.profiles.active=test --file pom.xml
      working-directory: ./PortalBackend/Java

    - name: Build and test docker image
      uses: docker/build-push-action@v2
      with:
        context: PortalBackend/Java
