name: Java CI

on:
  pull_request:
    types:
      - opened
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: checkout the code
      uses: actions/checkout@v3

    - name: Set up Java version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven # also packages the application
      run: mvn -B package -DskipTests --file pom.xml
      working-directory: ./PortalBackend/Demo

    - name: Run Tests with Maven # also packages the application
      run: mvn -B test -Dspring.profiles.active=test --file pom.xml
      working-directory: ./PortalBackend/Demo